services:
  emojibot:
    build: .
    env_file:
      - .env
    environment:
      STATS_FILE: /data/stats.json
      PRESETS_FILE: /data/presets.json
      SETTINGS_FILE: /data/settings.json
    restart: unless-stopped
    volumes:
      - emojibot_data:/data

volumes:
  emojibot_data:
